import { MenuItem } from './types';

export const WHATSAPP_NUMBER = '5491123456962';
export const WHATSAPP_LINK = `https://wa.me/${WHATSAPP_NUMBER}`;
export const ADDRESS = 'Malvinas Argentinas 285, Caballito, CABA';
export const SLOGAN = 'Empanadas y canastitas que son un gol';

export const HORARIOS = {
  semana: '12:00 – 15:00 / 19:00 – 23:00',
  domingo: '19:00 – 23:00',
};

export const menuItems: MenuItem[] = [
  // ── EMPANADAS ──
  {
    id: 'emp-carne-cuchillo',
    name: 'Carne a Cuchillo',
    description: 'La clásica de siempre, con carne cortada a mano y el toque justo de especias.',
    price: 3200,
    category: 'empanada',
    image: '/img/empanada.png',
    featured: true,
  },
  {
    id: 'emp-carne-suave',
    name: 'Carne Suave',
    description: 'Sabor tradicional con carne tierna y jugosa, perfecta para los más chicos.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  {
    id: 'emp-carne-picante',
    name: 'Carne Picante',
    description: 'Para los que les gusta el picante. Carne con ají molido y un toque de pimentón.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  {
    id: 'emp-carne-titi',
    name: 'Carne Titi',
    description: 'Nuestra receta secreta. La especialidad de la casa que no te podés perder.',
    price: 3200,
    category: 'empanada',
    image: '/img/empanada.png',
    featured: true,
  },
  {
    id: 'emp-pollo-verdeo',
    name: 'Pollo al Verdeo',
    description: 'Pollo desmenuzado con cebolla de verdeo salteada. Suave y sabrosa.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  {
    id: 'emp-jamon-queso',
    name: 'Jamón y Queso',
    description: 'El clásico que nunca falla. Jamón cocido y queso derretido.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  {
    id: 'emp-4-quesos',
    name: '4 Quesos',
    description: 'Mezcla irresistible de cuatro quesos fundidos. Para los queseros.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  {
    id: 'emp-queso-cebolla',
    name: 'Queso y Cebolla',
    description: 'Queso cremoso con cebolla caramelizada. Dulce y salada a la vez.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  {
    id: 'emp-verdura',
    name: 'Verdura',
    description: 'Acelga, cebolla y condimentos. Liviana y llena de sabor.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  {
    id: 'emp-roquefort-apio',
    name: 'Roquefort y Apio',
    description: 'Combinación gourmet de roquefort cremoso con apio fresco.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  {
    id: 'emp-atun',
    name: 'Atún',
    description: 'Atún con cebolla y huevo. Un clásico de las empanadas argentinas.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  {
    id: 'emp-caprese',
    name: 'Caprese',
    description: 'Tomate, mozzarella y albahaca. Fresca y deliciosa.',
    price: 3000,
    category: 'empanada',
    image: '/img/empanada.png',
  },
  // ── CANASTITAS ──
  {
    id: 'can-lomo-mostaza',
    name: 'Lomo a la Mostaza',
    description: 'Tiernos trozos de lomo con salsa de mostaza en canasta crocante.',
    price: 3200,
    category: 'canastita',
    image: '/img/canastita.png',
    featured: true,
  },
  {
    id: 'can-lomo-cheddar',
    name: 'Lomo con Cheddar',
    description: 'Lomo jugoso bañado en cheddar fundido. Explosión de sabor.',
    price: 3200,
    category: 'canastita',
    image: '/img/canastita.png',
  },
  {
    id: 'can-camarones',
    name: 'Camarones',
    description: 'Camarones frescos con salsa especial. Nuestra joya premium.',
    price: 3700,
    category: 'canastita',
    image: '/img/canastita.png',
  },
  {
    id: 'can-mejillon',
    name: 'Mejillón',
    description: 'Mejillones tiernos con toque de limón y perejil.',
    price: 3700,
    category: 'canastita',
    image: '/img/canastita.png',
  },
  {
    id: 'can-palmitos',
    name: 'Palmitos',
    description: 'Palmitos cremosos en canasta dorada. Suave y delicada.',
    price: 3000,
    category: 'canastita',
    image: '/img/canastita.png',
  },
  {
    id: 'can-panceta-ciruela',
    name: 'Panceta y Ciruela',
    description: 'Panceta crocante con ciruela. El equilibrio perfecto dulce-salado.',
    price: 3000,
    category: 'canastita',
    image: '/img/canastita.png',
  },
  {
    id: 'can-humita',
    name: 'Humita',
    description: 'Choclo cremoso con especias. Sabor bien del norte argentino.',
    price: 3000,
    category: 'canastita',
    image: '/img/canastita.png',
  },
  {
    id: 'can-calabaza',
    name: 'Calabaza',
    description: 'Calabaza asada con un toque de nuez moscada. Dulce natural.',
    price: 3000,
    category: 'canastita',
    image: '/img/canastita.png',
  },
];
